const $=s=>document.querySelector(s);const KEY='peakBadgeProgress.v1';let badges=[],progress={};let deferredPrompt=null;
async function init(){try{badges=await (await fetch('badges.json')).json()}catch(e){$('#badgeList').innerHTML='<p>Badge data could not be loaded. Serve this folder over HTTP(S) rather than opening index.html directly.</p>';return}progress=JSON.parse(localStorage.getItem(KEY)||'{}');fillBiomes();bind();render();if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js').catch(()=>{})}
function fillBiomes(){[...new Set(badges.flatMap(b=>b.biome.split(' / ')))].sort().forEach(x=>$('#biome').insertAdjacentHTML('beforeend',`<option>${x}</option>`))}
function bind(){['search','status','biome','difficulty','sort'].forEach(id=>$('#'+id).addEventListener('input',render));$('#clear').onclick=()=>{if(confirm('Reset all earned badges?')){progress={};save();render()}};window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#install').hidden=false});$('#install').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('#install').hidden=true}}}
function save(){localStorage.setItem(KEY,JSON.stringify(progress))}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function render(){let q=$('#search').value.trim().toLowerCase(),st=$('#status').value,bio=$('#biome').value,dif=$('#difficulty').value,sort=$('#sort').value;let list=badges.filter(b=>{let hay=[b.name,b.description,b.tip,b.biome,b.difficulty].join(' ').toLowerCase();let ok=!q||hay.includes(q);ok&&=st==='all'||(st==='done'&&progress[b.id])||(st==='todo'&&!progress[b.id]);ok&&=bio==='all'||b.biome.split(' / ').includes(bio);ok&&=dif==='all'||b.difficulty===dif;return ok});if(sort==='name')list.sort((a,b)=>a.name.localeCompare(b.name));if(sort==='difficulty'){let n={Easy:1,Medium:2,Hard:3};list.sort((a,b)=>n[a.difficulty]-n[b.difficulty])}$('#badgeList').innerHTML=list.map(card).join('');$('#empty').hidden=!!list.length;$('#resultCount').textContent=`Showing ${list.length} of ${badges.length} badges`;document.querySelectorAll('.check').forEach(x=>x.onchange=()=>{progress[x.dataset.id]=x.checked;if(!x.checked)delete progress[x.dataset.id];save();render()});let done=badges.filter(b=>progress[b.id]).length;$('#progressText').textContent=`${done} / ${badges.length}`;$('#progressBar').style.width=`${done/badges.length*100}%`}
function card(b){let done=!!progress[b.id];return `<article class="badge ${done?'done':''}"><div class="badge-main"><img class="badge-icon" src="${b.icon}" alt=""><div><h2>${esc(b.name)}</h2><p>${esc(b.description)}</p><div class="meta"><span class="pill">${esc(b.biome)}</span><span class="pill ${b.difficulty.toLowerCase()}">${esc(b.difficulty)}</span></div></div><input class="check" data-id="${b.id}" type="checkbox" ${done?'checked':''} aria-label="Mark ${esc(b.name)} earned"></div><details class="details"><summary>Tips & details</summary><div class="detail-body"><p class="tip"><strong>Tip:</strong> ${esc(b.tip)}</p><p>${esc(b.details)}</p></div></details></article>`}
init();
